config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"
  
  resources :products do
    put 'add_cart', on: :member
    put 'remove_cart', on: :member
    get 'search', on: :collection
    get 'catalog', on: :member
  end

  resources :categories

  resources :users do
    get 'cart', on: :member
    resources :orders, except: [:edit, :destroy, :update] do
      put 'authorized', on: :member
      put 'unauthorized', on: :member
    end
  end

  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  validates :name, presence: :true

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def edit
    @categoriesproduct = Categoriesproduct.select(:category_id).distinct
    @existing_categories = Category.all
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :address, :contact, :dob)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def cart
    @categoriesproduct = Categoriesproduct.select(:category_id).distinct
    @existing_categories = Category.all
    @cart = $redis.hgetall current_user.id
  end

  def destroy
    redirect_to root_path if current_user.destroy
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/cart.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center mb-0 pb-0">
      <h2 class="card-title">Your Shopping Cart Items</h2>
    </div>
  </div>

  <% if @cart.empty? %>
    <div class="row">
      <div class="col-md-12">No items in shopping cart, back to home page <%= link_to 'Home', url_for(root_path), class: "btn btn-secondary" %></div>
    </div>
  <% else %>
    <% total = 0 %>
    <% @cart.each do |product_id, qty| %>
      <div class="row">
        <div class="col-md-12 m-0 p-2">
          <table border="1" width="100%"><tr>
            <td width="20%" class="text-center">
              <%= filestack_image Product.find(product_id).filepicker_url, transform: filestack_transform.resize(width:150, height:150)  %>
            </td>

            <td width="60%" class="pt-2 pl-2">
              <h5 class="card-title font-weight-bold"><%=Product.find(product_id).name %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= number_to_currency(price = Product.find(product_id).price) %> each</h6>
              <p class="card-text"><%=Product.find(product_id).description %><p></br>
              <strong>Subtotal: </strong><%= number_to_currency(subtotal = price * qty.to_i) %>
              <% total += subtotal %>
            </td>
          
            <td width="20%" class="text-center"> 
              <h5 class="card-title font-weight-bold">Quantity</h5>
              <p class="card-text">
                <%= link_to '-', remove_cart_product_path(product_id), method: :put, class: "btn btn-outline-danger btn-small font-weight-bold" %>
                &nbsp <%= qty %> &nbsp 
                <%= link_to '+', add_cart_product_path(product_id), method: :put, class: "btn btn-outline-success btn-small font-weight-bold" %>
              </p>
            </td>
          
          </tr></table>
        </div>
      </div>
    <% end %>

      <div class="row">
        <div class="col-md-12 m-0 p-2">
          <table width="100%"><tr>
            <td width="20%" class="text-center"><h5 class="card-title font-weight-bold">Grand Total: </h5></td>
            <td width="60%"><h5 class="card-title font-weight-bold pl-3"><%= number_to_currency(total) %></h5></td>
            <td width="20%" class="text-center"><p><%= link_to 'Checkout', new_user_order_path(current_user), method: :get, class: "btn btn-outline-primary", data: { confirm: "This will redirect you to checkout, proceed?"} %>
            <%= link_to 'Back', url_for(:back), class: "btn btn-secondary" %>
            </p></td>
          </tr></table>
        </div>
      </div>


  <% end %>

</div>

app/views/users/index.html.erb
<h1>User index page</h1>