config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"
  
  resources :products do
    put 'add_cart', on: :member
    put 'remove_cart', on: :member
    get 'search', on: :collection
    get 'catalog', on: :member
  end

  resources :categories

  resources :users do
    get 'cart', on: :member
    resources :orders, except: [:edit, :destroy, :update] do
      put 'authorized', on: :member
      put 'unauthorized', on: :member
    end
  end

  

end

app/models/order.rb
class Order < ApplicationRecord


  has_many :ordersproducts
  has_many :products, through: :ordersproducts

  
  

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @categoriesproduct = Categoriesproduct.select(:category_id).distinct
    @existing_categories = Category.all

    if current_user.try(:admin?)
      @orders = Order.all.order('created_at DESC')
      @pending_orders = Order.where(status: 'In Progress').order('created_at DESC')
      @rejected_orders = Order.where(status: 'Failed').order('created_at DESC')
    else
      @orders = current_user.orders.order('created_at DESC')
    end
  end

  def show
    @categoriesproduct = Categoriesproduct.select(:category_id).distinct
    @existing_categories = Category.all
    @products = Ordersproduct.all.where(order_id: params[:id])
    @uniq_products = Order.find(params[:id]).products.uniq
    @order_details = Order.includes(:user).find(params[:id])
  end

  def new
    gon.client_token = generate_client_token
    @categoriesproduct = Categoriesproduct.select(:category_id).distinct
    @existing_categories = Category.all
    @cart = $redis.hgetall current_user.id
  end

  def create
    result = Braintree::Transaction.sale(
      amount: params[:total],
      payment_method_nonce: params[:payment_method_nonce])
      if result.success?
        order = $redis.hgetall current_user.id
        Order.create(user_id: current_user.id, transaction_num: result.transaction.id, status: 'In Progress')
        
        order.each do |product, qty| 
          qty.to_i.times do
          Ordersproduct.create(product_id: product.to_i, order_id: Order.last.id)
          end
        end
        
        $redis.del current_user.id
        OrderMailer.payment_success_email(current_user).deliver_later 
        flash[:notice] = "Checkout completed"
        redirect_to root_url
      else
        flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
        gon.client_token = generate_client_token
        @cart = $redis.hgetall current_user.id
        render :new
      end
  end

  def authorized
    @order = Order.find(params[:id])
    @order.status = 'Delivered'
    OrderMailer.delivered_email(@order.user).deliver_later 
    if @order.save
      redirect_to user_orders_path
      flash[:notice] = 'Order ID: ' + @order.id.to_s + ' authorized' 
    else
      redirect_to user_orders_path
      flash[:alert] = 'Order ID: ' + @order.id.to_s + ' authorization failed' 
    end  
  end

  def unauthorized
    @order = Order.find(params[:id])
    @order.status = 'Failed'
    OrderMailer.rejected_email(@order.user).deliver_later 
    if @order.save
      redirect_to user_orders_path
      flash[:alert] = 'Order ID: ' + @order.id.to_s + ' rejected' 
    end  
  end

  private

  def order_params
    params.require(:product).permit(:status)
  end

  def generate_client_token
    Braintree::ClientToken.generate
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<h1>My Cart</h1>

<% total_price = 0 %>
<% @uniq_products.each do |product| %>

  <div class="myproducts">
    <p id="product">
      <strong><%= product.name %> : </strong>
      <%= number_to_currency(price =product.price) %>
      qty: <%= qty = @products.where(id: product).count %>
      total: <%= number_to_currency(subtotal = price * qty) %>
      <% total_price = total_price + subtotal %>
    </p>
    <hr>

  </div>
<% end %>
<u>
<strong>
  Grand Total: 
  <%= number_to_currency(total_price) %>
</strong>
</u>
<br>
<hr>
<%= link_to 'Order History', user_orders_path%>

app/views/orders/index.html.erb
<% if current_user.try(:admin?) %>
  <div class="container">
    <div class="row">
      <div class="col-md-12 p-0 mt-3 mb-0 d-flex justify-content-center">
        <h3 class="card-title">Hello <strong><%= current_user.name %></strong>, welcome to MOMS (Marketplace Order Management System)</h3>  
      </div>
    </div>

    <div class="row d-flex">
      <div class="col-md-6 border m-0 text-center">
        <h3>Pending Order(s)</h3>
        <h5 class="bg-success"><%= notice %></h5>
        <h5 class="bg-danger"><%= alert %></h5>
        <table width="100%">
          <tr>
            <th>ID</th>
            <th>Trasaction No.</th>
            <th>Braintree Status</th>
            <th>Admin Actions</th>  
          </tr>
         
        <% @pending_orders.each do |po| %>
          <tr>
            <td><%= link_to po.id, user_order_path(po.user_id, po) %></td>
            <td><%= po.transaction_num %></td>

            <% collection = Braintree::Transaction.search  %>
            <% collection.each do |transaction| %>
              <% if po.transaction_num == transaction.id %>
                <td><%= transaction.status %></td>

                <% if transaction.status == "authorized" %>
                  <td>
                    <%= link_to 'Authorize', authorized_user_order_path(po.user_id, po), method: :put, class: "btn btn-outline-success" %>
                    <%= link_to 'Reject', unauthorized_user_order_path(po.user_id, po), method: :put, class: "btn btn-danger", data: { confirm: 'Confirm reject order?'} %>
                  </td>
                <% else %>
                  <td>
                    <%= link_to 'Authorize', authorized_user_order_path(po.user_id, po), method: :put, class: "btn btn-outline-success disabled"%>
                    <%= link_to 'Reject', unauthorized_user_order_path(po.user_id, po), method: :put, class: "btn btn-danger", data: { confirm: 'Confirm reject order?'} %>
                  </td>
                <% end %>
              <% end %>
            <% end %>
          </tr>
        <% end %>
        </table>
      </div>

      <div class="col-md-6 border m-0 text-center">
        <h3>Failed Order(s)</h3>
        <table width="100%">
          <tr>
            <th>ID</th>
            <th>Created at</th>
            <th>Rejected on</th>
            <th>Transaction No.</th>
          </tr>
        
        <% @rejected_orders.each do |ro| %>
          <tr>
            <td><%= link_to ro.id, user_order_path(ro.user_id, ro) %></td>
            <td><%= ro.created_at.strftime("%d/%m/%Y, %I:%M%p") %></td>
            <td><%= ro.updated_at.strftime("%d/%m/%Y, %I:%M%p") %></td>
            <td><%= ro.transaction_num %></td>
          </tr>
        <% end %>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8 offset-md-2 text-center">
        <h3>Historical Summary</h3>
        <table width="100%" border="1"><tr>
          <th>ID</th>
          <th>Status</th>
          <th>Datetime</th>
          <th>Transaction No.</th>
        </tr>

        <% @orders.each do |order| %>
        <tr>
          <td><p><%= link_to order.id, user_order_path(order.user_id, order) %></p></td>
          <td><% if order.status == "Delivered" %>
              <b class="text-success"><%= order.status %></b>
            <% elsif order.status == "In Progress" %>
              <b class="text-warning"><%= order.status %></b>
            <% else %>
              <b class="text-danger"><%= order.status %></b>
            <% end %>
          </p></td>
          <td><%= order.created_at.strftime("%d/%m/%Y, %I:%M%p") %></td>
          <td><%= order.transaction_num %></td>

        </tr>

        <% end %>

        </table>
      </div>
    </div>

  </div>

<% else %>

  <div class="container">
    <div class="row">
      <div class="col-md-12 p-0 mt-3 mb-0 d-flex justify-content-center">
        <h3 class="card-title font-weight-light">Your order history</h3>
      </div>
    </div>

    <% @orders.each do |order| %>
      <div class="row">
        <div class="col-md-6 offset-md-3 border-top border-bottom mb-0">
          <p><strong>Transaction Number:</strong> <%= order.transaction_num %></p>
          <p><strong>Order Status: </strong>
            <% if order.status == "Delivered" %>
              <b class="text-success"><%= order.status %></b>
            <% elsif order.status == "In Progress" %>
              <b class="text-warning"><%= order.status %></b>
            <% else %>
              <b class="text-danger"><%= order.status %></b>
            <% end %>
          </p>
          <p><strong>Payment Time: </strong><%= order.created_at.strftime("%d/%m/%Y, %I:%M%p") %></p>
          <p><%= link_to 'View order details', user_order_path(current_user, order) %></p>
        </div>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="actions">
          <%= link_to 'Back', url_for(:back), class: "btn btn-secondary" %>
        </div>
      </div>
    </div>

  </div>

<% end %>

app/views/orders/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center mb-0 pb-0">
      <h2 class="card-title">You're now checking out your shopping cart</h2>
    </div>
  </div>


  <% total = 0 %>
  <% @cart.each do |product_id, qty| %>
    <div class="row">
      <div class="col-md-12 m-0 p-2">
        <table border="1" width="100%"><tr>
          <td width="20%" class="text-center">
            <%= filestack_image Product.find(product_id).filepicker_url, transform: filestack_transform.resize(width:150, height:150)  %>
          </td>

          <td width="60%" class="pt-2 pl-2">
            <h5 class="card-title font-weight-bold"><%=Product.find(product_id).name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= number_to_currency(price = Product.find(product_id).price) %> each</h6>
            <p class="card-text"><%=Product.find(product_id).description %><p></br>
            <strong>Subtotal: </strong><%= number_to_currency(subtotal = price * qty.to_i) %>
            <% total += subtotal %>
          </td>
        
          <td width="20%" class="text-center"> 
            <h5 class="card-title font-weight-bold">Quantity</h5>
            <p class="card-text">
               <%= qty %> 
            </p>
          </td>
        </tr></table>
      </div>
    </div>
  <% end %>

  </br></br>

  <%= form_tag user_orders_path(current_user, total: total) do%>
    <h4 class="text-center">Please enter your payment details</h4>
    <div id="dropin"></div>
    <p><strong>Grand Total: </strong><%= number_to_currency(total) %></p>
    <p><%= submit_tag "Pay", class: "btn btn-primary" %>
    <%= link_to 'Back', url_for(:back), class: "btn btn-secondary" %>
    </p>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 border-bottom mb-0">
      <h5>Transaction ID: <strong><%= @order_details.transaction_num %></strong></h5>
      <h5>Executed by: <strong><%= @order_details.user.name %></strong></h5>
      <h5>User ID: <strong><%= @order_details.user_id%></strong></h5>
      <h5>Created DateTime: <strong><%= @order_details.created_at.strftime("%d/%m/%Y, %I:%M%p") %></strong></h5>
    </div>
  </div>

  <% total_price = 0 %>
  <% @uniq_products.each do |product| %>
    <div class="row">
      <div class="col-md-6 offset-md-3 border-top border-bottom mb-0">
        <table width="100%"><tr>
          <td width="20%"><%= filestack_image product.filepicker_url, transform: filestack_transform.resize(width:150, height:150), class: "card-img-top" %></td>
          <td width="80%" class="pl-4">
            <p><strong>Name: </strong><%= product.name %></p>
            <p class="card-subtitle mb-2 text-muted"><%= number_to_currency(price =product.price) %> each</p>
            <p><strong>Quantity: </strong><%= qty = @products.where(product_id: product).count %></p>
            <p><strong>Sub-Total: </strong><%= number_to_currency(subtotal = price * qty) %></p>
            <% total_price = total_price + subtotal %>
          </td>
        </tr></table>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 offset-md-3">
      <p><strong>Grand Total: </strong><%= number_to_currency(total_price) %></p>
      <%= link_to 'Back', url_for(:back), class: "btn btn-secondary" %>
    </div>
  </div>


</div>