config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"
  
  resources :products do
    put 'add_cart', on: :member
    put 'remove_cart', on: :member
    get 'search', on: :collection
    get 'catalog', on: :member
  end

  resources :categories

  resources :users do
    get 'cart', on: :member
    resources :orders, except: [:edit, :destroy, :update] do
      put 'authorized', on: :member
      put 'unauthorized', on: :member
    end
  end

  

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :ordersproducts
  has_many :orders, through: :ordersproducts
  has_many :categoriesproduct, dependent: :destroy
  has_many :categories, through: :categoriesproduct

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :authenticate_user!, except: [:index, :search, :catalog]
  def index
    @products = Product.all
    repeated_codes
    respond_to do |format|
      format.html
      format.json { render json: @products }
    end
  end

  def create
    @product = Product.create(product_params)
    
      @pcat = Category.find(params[:pcat]) if params[:pcat] #index box array

    if @product.save 
      if params[:pcat]
        @pcat.each do |pc|
          Categoriesproduct.create(product: @product, category: pc)
        end
      end
      redirect_to root_path
    end
  end

  def edit
    session[:return_to] ||= request.referer #store requesting url in session hash
    @product = Product.all.find(params[:id])
    @existing_categories = Category.all 
  end

  def update
    @product = Product.find(params[:id])
    @pcat = Category.find(params[:pcat]) if params[:pcat] != nil #index box array

    cleanse_cat = Categoriesproduct.where(product: @product)  #cleanse Categoriesproduct of existing product id
    cleanse_cat.each do |cleanse|
      cleanse.destroy
    end

    if @product.update(product_params)  
      if @pcat != nil
        @pcat.each do |pc|
          Categoriesproduct.create(product: @product, category: pc)
        end
      end
      redirect_to session.delete(:return_to) #redirect to stored session path

    end
  end

  def destroy
    product = Product.find(params[:id])
    if product.destroy
      redirect_to root_path
    end
  end

  def add_cart
    $redis.hincrby current_user.id, params[:id], 1
    product = Product.find(params[:id])
    flash[:notice] = product.name + " added to cart"
    redirect_to request.referrer
  end

  def remove_cart
    count = $redis.hincrby current_user.id, params[:id], -1
    if count == 0
      $redis.hdel current_user.id, params[:id]
    end
    redirect_to cart_user_path(current_user)
  end

  def search
    repeated_codes
    
    @search_params = params[:q]
    @product_search = Product.where("name ILIKE ?", "%#{@search_params}%")
  end

  def catalog
    repeated_codes
    
    @catalog_params = params[:id]
    @catalog_name = Category.find(@catalog_params)
    @catalog_search = Categoriesproduct.where(category_id: @catalog_params)
    
    catalog = []
    @catalog_search.each do |c|
      catalog << c.product_id
    end

    @catalog = Product.where(id: catalog)
  end

  private

  def product_params
    params.require(:product).permit(:name, :filepicker_url, :description, :price, :pcat)
  end

  def repeated_codes
    @product = Product.new
    @category = Category.new
    @categoriesproduct = Categoriesproduct.select(:category_id).distinct
    @existing_categories = Category.all
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_admin_console.html.erb
<% if current_user.try(:admin?) %>
  <div class="row admin-console">
    <div class="col-sm-12 d-flex justify-content-center font-weight-light admin-console-col" id="console">
      <h5>Hello <strong><%= current_user.name %></strong>, welcome to the administrative console (Click to hide/open)</h5>
    </div>
  </div>

<div id="console-form">
  <div class="row admin-console">
    <div class="col-md-6 border-right border-top admin-console-col">
      <h3 class="text-center"><u>Add a new product</u></h3>
      <%= form_for @product, url: products_path do |f| %>
        <h5 class="card-title font-weight-light">Name</h5>
        <%= f.text_field :name, class: "form-control", placeholder: "Product name" %></br>

        <h5 class="card-title font-weight-light">Description</h5>
        <%= f.text_area :description, class: "form-control", rows: "3", placeholder: "Product description" %></br>
        
        <h5 class="card-title font-weight-light">Category (choose at least 1)</h5>
          <% @existing_categories.all.each do |category| %>
            <%= check_box_tag "pcat[]", category.id %><%= category.category %> &nbsp
          <% end %>

        <h5 class="card-title font-weight-light">Price</h5>
        <%= f.text_field :price, class: "form-control", placeholder: "Price in 2 decimals point" %></br>

         <%= f.filestack_field :filepicker_url, "Upload product picture", class: "btn btn-primary" %></br>
        </br>

        <p><%= f.submit "Create product", class: "btn btn-primary" %></p>
      <% end %>
    </div>

    <div class="col-md-6 border-left border-top admin-console-col">
      <h3 class="text-center"><u>Category Management</u></h3>
      <%= form_for @category, url: categories_path(@products) do |c| %>
       <h5 class="card-title font-weight-light">Add new Category</h5>
       <table><tr>
          <td width="100%"><%= c.text_field :category, class: "form-control", placeholder: "Product Category" %></td>
          <td><%= c.submit "submit", class: "btn btn-primary" %></td>
        </tr></table>
        </br>
      <% end %>

      <h5 class="card-title font-weight-light text-center">Existing Categories</h5>
      <div class="list-group">
        <% @existing_categories.each do |x| %>
          
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <%= form_for @category, url: category_path(x), method: :put do |f| %>
              <table><tr>
                <td width="100%">
                  <%= f.text_field :category, placeholder: x.category, class: "form-control edit-category-placeholder" %>
                </td>
              
                <td>
                  <%= f.submit "update", class: "btn btn-outline-primary" %>
                </td>
                <td>
                  <%= link_to 'Remove', category_path(x), method: :delete, class: "btn btn-danger", data: { confirm: 'This will remove the category, procced?' } %>
                </td>
              </tr></table>

            <% end %> 
         
          </li>

        <% end %>
      </div>
    </div>
  </div>
 </div>
<% end%>

app/views/products/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="/assets/Pic1" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/assets/Pic2" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/assets/Pic3" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/products/catalog.html.erb
<div class="container">

  <%= render partial: "admin_console" %>  

  <div class="row">
    <%= render partial: "carousel" %>  
  </div>

  <div class="row">

    <div class="col-md-12 d-flex justify-content-center mt-4">
      <h2>Showing <strong><%= @catalog_name.category %></strong> catalog</h2>
    </div>

     <% @catalog.each do |p| %>
      <div class="col-md-3 d-flex flex-column justify-content-between border-left border-right">
        
        <%= filestack_image p.filepicker_url, transform: filestack_transform.resize(width:250, height:250), class: "card-img-top" %>

        <div>
          <h3 class="card-title product-bg"><%= p.name %></h3>
          <h6 class="card-subtitle mb-2 text-muted"><%= number_to_currency(p.price) %></h6>
          <p class="card-text"><%= p.description %></p>
          <p class="card-text"><strong>Category: </strong>
            <% if p.category_ids.length > 0 %>
              <% @existing_categories.each do |existing_cat| %>
                <% p.category_ids.each do |product_cat| %>
                  <%= existing_cat.category if existing_cat.id == product_cat %>
                <% end %>
              <% end %>
            <% else %>
              Unassigned
            <% end %>
          </p>
          </br>
        </div>

        <div>
          <table>
            <tr>
              <% if current_user.try(:admin?) %>
                <td><%= button_to 'Edit', edit_product_path(p), method: :get, class: "btn btn-outline-primary" %></td>
                <td><%= button_to 'Destroy', p, method: :delete, class: "btn btn-danger", data: { confirm: 'This will remove the product, are you sure you want to proceed' } %></td>
              <% else %>
                <td><%= link_to 'Add to cart', add_cart_product_path(p), method: :put, class: "btn btn-outline-success" %></td>
              <% end%>
            </tr>
          </table>
        </div>


      </div>
    <% end %>

  </div>

</div>

app/views/products/edit.html.erb
<% if current_user.try(:admin?) %>
  <div class="container">
    <div class="row">

      <div class="col-md-12 d-flex justify-content-center font-weight-light">
        <h2>Edit product information for <strong><%= @product.name %></strong></h2>
      </div>

      <div class="col-md-4 offset-md-2">
        <h4 class="card-title text-center font-weight-light">Current image</h4>
        <%= filestack_image @product.filepicker_url, transform: filestack_transform.resize(width:200, height:200), class: "card-img-top" %>
      </div>

      <div class="col-md-4">
        <%= form_for @product, url: product_path, method: :put do |f| %>
          <h4 class="card-title font-weight-light">Name</h4>
          <%= f.text_field :name, class: "form-control" %></br>

          <h4 class="card-title font-weight-light">Description</h4>
          <%= f.text_area :description, class: "form-control", rows: "3" %></br>

          <h5 class="card-title font-weight-light">Category</h5>
          <% @existing_categories.each do |category| %>
            <%= check_box_tag "pcat[]", category.id %><%= category.category %>
          <% end %>

          <h4 class="card-title font-weight-light">Price</h4>
          <%= f.text_field :price, class: "form-control" %></br>
          
          <h4 class="card-title font-weight-light">Update Image <%= f.filestack_field :filepicker_url, "Select", class: "btn btn-primary"%></h4>
          </br>
          
          <%= f.submit "Update", class: "btn btn-primary" %>
          <%= button_to 'Return', root_path, class: "btn btn-secondary" %>
        <% end %>
      </div>

    </div>
  </div>
<% end%>

app/views/products/index.html.erb
<div class="container">
  
  <%= render partial: "admin_console" %>  

  <div class="row">
    <%= render partial: "carousel" %>  
  </div>

  <div class="row">

    <div class="col-md-12 d-flex justify-content-center mt-4 mb-0">
      <h2>The Marketplace</h2>
    </div>

    <% if notice %>
      <div class="col-md-12 d-flex justify-content-center m-0 p-0 bg-success">
        <h5 class="m-0 p-0"><%= notice %></h5>
      </div>
    <% end %>

    <% @products.each do |p| %>
      <div class="col-md-3 d-flex flex-column justify-content-between border-left border-right">
        
        <%= filestack_image p.filepicker_url, transform: filestack_transform.resize(width:250, height:250), class: "card-img-top" %>

        <div>
          <h3 class="card-title product-bg"><%= p.name %></h3>
          <h6 class="card-subtitle mb-2 text-muted"><%= number_to_currency(p.price) %></h6>
          <p class="card-text"><%= p.description %></p>
          <p class="card-text"><strong>Category: </strong>
            <% if p.category_ids.length > 0 %>
              <% @existing_categories.each do |existing_cat| %>
                <% p.category_ids.each do |product_cat| %>
                  <%= existing_cat.category if existing_cat.id == product_cat %>
                <% end %>
              <% end %>
            <% else %>
              Unassigned
            <% end %>
          </p>
          </br>
        </div>
        
        <div>
          <table>
            <tr>
              <% if current_user.try(:admin?) %>
                <td><%= button_to 'Edit', edit_product_path(p), method: :get, class: "btn btn-outline-primary" %></td>
                <td><%= button_to 'Destroy', p, method: :delete, class: "btn btn-danger", data: { confirm: 'This will remove the product, are you sure you want to proceed' } %></td>
              <% else %>
                <td><%= link_to 'Add to cart', add_cart_product_path(p), method: :put, class: "btn btn-outline-success" %></td>
              <% end%>
            </tr>
          </table>
        </div>
        
      </div>
    <% end %>
  
  </div>

</div>

app/views/products/search.html.erb
<div class="container">
  
  <%= render partial: "admin_console" %>  

  <div class="row">
    <%= render partial: "carousel" %>  
  </div>

  <div class="row">

    <div class="col-md-12 d-flex justify-content-center mt-4">
      <% if @search_params == "" %>
        <h2>Returning results for all products</h2>
      <% else %>
        <h2>You have Searched for <strong><%= @search_params %></strong></h2>
      <% end %>
    </div>

    <% @product_search.each do |p| %>
      <div class="col-md-3 d-flex flex-column justify-content-between border-left border-right">
        
        <%= filestack_image p.filepicker_url, transform: filestack_transform.resize(width:250, height:250), class: "card-img-top" %>

        <div>
          <h3 class="card-title product-bg"><%= p.name %></h3>
          <h6 class="card-subtitle mb-2 text-muted"><%= number_to_currency(p.price) %></h6>
          <p class="card-text"><%= p.description %></p>
          <p class="card-text"><strong>Category: </strong>
            <% if p.category_ids.length > 0 %>
              <% @existing_categories.each do |existing_cat| %>
                <% p.category_ids.each do |product_cat| %>
                  <%= existing_cat.category if existing_cat.id == product_cat %>
                <% end %>
              <% end %>
            <% else %>
              Unassigned
            <% end %>
          </p>
          </br>
        </div>

        <div>
          <table>
            <tr>
              <% if current_user.try(:admin?) %>
                <td><%= button_to 'Edit', edit_product_path(p), method: :get, class: "btn btn-outline-primary" %></td>
                <td><%= button_to 'Destroy', p, method: :delete, class: "btn btn-danger", data: { confirm: 'This will remove the product, are you sure you want to proceed' } %></td>
              <% else %>
                <td><%= link_to 'Add to cart', add_cart_product_path(p), method: :put, class: "btn btn-outline-success" %></td>
              <% end%>
            </tr>
          </table>
        </div>


      </div>
    <% end %>

  </div>

</div>