config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"
  
  resources :products do
    put 'add_cart', on: :member
    put 'remove_cart', on: :member
    get 'search', on: :collection
    get 'catalog', on: :member
  end

  resources :categories

  resources :users do
    get 'cart', on: :member
    resources :orders, except: [:edit, :destroy, :update] do
      put 'authorized', on: :member
      put 'unauthorized', on: :member
    end
  end

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
  </head>

  <body>
    <script src="https://js.braintreegateway.com/v2/braintree.js"></script>

    <nav class="navbar navbar-expand-lg navbar-light bg-light absolute-top">
    <div class="container">
      <a class="navbar-brand"><%= link_to 'The Marketplace', root_path %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            
            <li class="nav-item">
              <%= form_tag search_products_path, method: :get do %>
                <table><tr>
                  <td width="80%"><%= text_field_tag :q, params[:q], placeholder: "Search a product", class: "form-control" %></td>
                  <td><%= submit_tag 'Search', class: "btn btn-outline-success" %></td>
                </tr></table>
              <% end%>
            </li>

            <li class="nav-item">
              <div class="dropdown nav-link">
                <div class="dropdown-toggle navbar-items" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Catalog
                </div>
                <% if @categoriesproduct %>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <% @categoriesproduct.each do |c| %>
                      <% @existing_categories.each do |ec| %>
                        <% if c.category_id == ec.id %>
                          <div class="dropdown-item">
                            <%= link_to ec.category, catalog_product_path(ec), method: :get %>
                          </div>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>     
                <% end %>
              </div>
            </li>

            <% if current_user %>
              <li class="nav-item">
                <div class="dropdown nav-link">
                  <div class="dropdown-toggle navbar-items" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Account
                  </div>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <div class="dropdown-item"><%= link_to 'Edit Profile', edit_user_registration_path, method: :get %></div>
                    <div class="dropdown-item"><%= link_to 'Order History', user_orders_path(current_user) if current_user.orders.any? %></div>
                    <div class="dropdown-item"><%= link_to 'Close Account', user_path(current_user.id), method: :delete, data: {confirm:"Are you sure?"} %></div>
                  </div>             
                </div>
              </li>

              <% if current_user.try(:admin?) %>
                <li class="nav-item nav-link">
                  <%= link_to 'Orders', user_orders_path(current_user), class: "navbar-items"%>
                </li>
              <% else %>
                <li class="nav-item nav-link">
                  <% cart_count = 0 %>
                  <% cart_items = $redis.hgetall current_user.id %>
                  <% cart_items.each do |c| %>
                    <% item_count = c[1].to_i %>
                    <% cart_count += item_count %>
                  <% end %>
                  <%= link_to "Cart (#{cart_count})", cart_user_path(current_user), class: "navbar-items"%>
                </li>
              <% end %>

              <li class="nav-item nav-link">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-items" %>
              </li>
            <% else %>
              <li class="nav-item nav-link">
                <%= link_to "Log in", new_user_session_path, class: "navbar-items", method: :get %>
              </li>
            
              <li class="nav-item nav-link">
                <%= link_to "Sign Up", new_user_registration_path, class: "navbar-items", method: :get %>
              </li>

            <% end %>

          </ul>
        </div>
    </div>
    </nav>

    <%= yield %>

    <%= filestack_js_include_tag %>
    <%= filestack_js_init_tag %> 
  </body>
</html>